# syntax=docker/dockerfile:1

################################################################################
##                         START : EDIT  HERE : START                         ##
################################################################################

### 3.22.1
ARG alpine_digest="sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1"

################################################################################
##                           END : EDIT  HERE : END                           ##
################################################################################

FROM docker.io/library/alpine@${alpine_digest:?} AS fetch-and-decompress

ENV SOURCE_DATE_EPOCH="0"

VOLUME ["/bind"]

ENTRYPOINT ["/bin/fetch-and-decompress.sh"]

COPY \
  "./fetch-and-decompress.sh" \
  "/bin/"
